# Generated by Django 4.2.7 on 2024-09-04 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_course_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=1000, null=True)),
                ('link', models.URLField()),
                ('image', models.ImageField(null=True, upload_to='projects')),
            ],
        ),
    ]
